### ISSUE TITLE
Incorrect use of ParentDataWidget.

### ISSUE THREAD

**Issue by neutrin0x** [Rodiii/flutter_cupertino_radio_choice#1]
When I use the widget it says this error:
Incorrect use of ParentDataWidget.

It looks fine and everything seems to work properly but debug console throw that all the time.

**Comment by Rodiii** [comment]
Hi @neutrin0x , Could you please post example code that I can reproduce your issue?

**Comment by odaynasser** [comment]
i have the same issue and this is the code 
 ```
 @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Column(
        children: [
          SizedBox(
            height: 45,
          ),
          Box(
            child: Column(children: <Widget>[
              Align(
                alignment: Alignment.centerLeft,
                child: Text(
                  'Weight System',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
                ),
              ),
              SizedBox(
                height: 10,
              ),
              CupertinoRadioChoice(
                  selectedColor: AppColor.selectedMenuItemColor,
                  notSelectedColor: AppColor.lightText,
                  choices: {
                    'kg': 'Kilograms',
                    'lb': 'Pounds',
                  },
                  onChange: (selectedGender) {},
                  initialKeyValue: 'kg')
            ]),
          ),
        ],
      ),
    );
  }

  selectWeight(String weightKey) {
    print(weightKey);
  }
```

**Comment by odaynasser** [comment]
this is the error:
```
Performing hot reload...
Syncing files to device iPhone 11 Pro...

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.
The ParentDataWidget Flexible(flex: 1) wants to apply ParentData of type FlexParentData to a
RenderObject, which has been set up to accept ParentData of incompatible type WrapParentData.
Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically,
Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a Wrap widget.
The ownership chain for the RenderObject that received the incompatible parent data was:
  _GestureSemantics ← RawGestureDetector ← GestureDetector ← CupertinoButton ← Flexible ← Wrap ←
CupertinoRadioChoice ← Column ← Padding ← DecoratedBox ← ⋯

Another exception was thrown: Incorrect use of ParentDataWidget.
Reloaded 3 of 918 libraries in 300ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Flexible(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type WrapParentData.

Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically, Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a Wrap widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  _GestureSemantics ← RawGestureDetector ← GestureDetector ← CupertinoButton ← Flexible ← Wrap ← CupertinoRadioChoice ← Column ← Padding ← DecoratedBox ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5689:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5705:6)
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:4939:15)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:4942:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Incorrect use of ParentDataWidget.
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by dnsflnv** [comment]
```
Widget buildSelectionButton(dynamic key, String value,
      {bool selected = false}) {
    return Container( // Flexible to Container
        child: CupertinoButton(
            disabledColor:
                selected ? widget.selectedColor : widget.notSelectedColor,
            color: selected ? widget.selectedColor : widget.notSelectedColor,
            padding: const EdgeInsets.all(10.0),
            child: Text(value),
            onPressed: !widget.enabled || selected
```

**Comment by AlexSavinien** [comment]
Hey there, got the same issue
```
CupertinoRadioChoice(
      choices: model.paiementTypes,
      onChange: model.setSelectedPaiementType,
      initialKeyValue: model.paiementTypes['cb'],
)
```

```
Map<String, String> _paiementTypes = {
    'cb': 'CB',
    'cash': 'Cash',
    'cheque': 'Chéque',
    'amo': 'AMO',
    'virement': 'Virement'
  };
  Map<String, String> get paiementTypes => _paiementTypes;

  String _selectedPaiementType;
  String get selectedPaiment => _selectedPaiementType;
  void setSelectedPaiementType({String newPaiementType}) {
    _selectedPaiementType = newPaiementType;
    print('New selected paiement type : $_selectedPaiementType');
  }
```


Any solution ?

**Comment by odaynasser** [comment]
for those still stuck - there's this lib which i switched to https://pub.dev/packages/toggle_switch

**Comment by Rodiii** [comment]
Hi all, sorry for the late response.

I just merged the fix by @filonov and pushed it to pub.dev (=> version 1.0.1).
This should fix this issue.

Thanks a lot @filonov!
